# Generated by Django 3.1.5 on 2021-01-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_type', models.CharField(choices=[('EXE', 'Ćwiczenia'), ('LAB', 'Laboratorium'), ('LEC', 'Wykład'), ('SEM', 'Seminarium')], max_length=3)),
                ('group_number', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Authorized',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anote.user')),
            ],
            bases=('anote.user',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('U', 'Niezadeklarowane'), ('D', 'Zadeklarowane'), ('F', 'Skończone')], default='U', max_length=1)),
                ('text_style', models.CharField(choices=[('LTX', 'Latex'), ('MD', 'Markdown'), ('TXT', 'Text')], default='TXT', max_length=3)),
                ('contents', models.TextField(default='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anote.user')),
                ('classes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anote.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_style', models.CharField(choices=[('LTX', 'Latex'), ('MD', 'Markdown'), ('TXT', 'Text')], max_length=3)),
                ('contents', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anote.user')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anote.note')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anote.subject'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField()),
                ('classes_type', models.CharField(choices=[('EXE', 'Ćwiczenia'), ('LAB', 'Laboratorium'), ('LEC', 'Wykład'), ('SEM', 'Seminarium')], max_length=3)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anote.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anote.user')),
            ],
            options={
                'unique_together': {('user', 'subject', 'group_number', 'classes_type')},
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='authorized',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anote.authorized'),
        ),
    ]
